# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='data timestamp')),
                ('status_code', models.IntegerField()),
                ('load_time', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=25)),
                ('site_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intuit_site_check.WebSite'),
        ),
    ]
