# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intuit_site_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='site_id',
            field=models.CharField(default='site_id', max_length=25),
        ),
    ]
