# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration***REMOVED***:

    dependencies = [
        ('intuit_site_check', '0002_website_site_id'***REMOVED***,
    ***REMOVED***

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='timestamp',
            field=models.DateTimeField(***REMOVED***,
        ***REMOVED***,
    ***REMOVED***
