# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration***REMOVED***:

    dependencies = [
        ('intuit_site_check', '0003_auto_20161026_2307'***REMOVED***,
    ***REMOVED***

    operations = [
        migrations.AddField(
            model_name='website',
            name='on_error_message',
            field=models.BooleanField(default=False***REMOVED***,
        ***REMOVED***,
    ***REMOVED***
