# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intuit_site_check', '0004_website_on_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='on_error_message',
        ),
    ]
